### ISSUE TITLE
Лучше назвать clear и не удалять всё, а записывать пустой список

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-ShoppingCalculator#17]
https://github.com/alinagaripova/homework-ShoppingCalculator/blob/907fbf0bcdc6a159b7e7620071ae7c4702ddee92/src/js/storage.js#L47

**Comment by alinagaripova** [comment]
removeItem заменила на clear. 
https://github.com/alinagaripova/homework-ShoppingCalculator/blob/e489a908ebff865de44233d5b618993ea7df5016/src/js/storage.js#L46-L47
Но как не удалять все и записать пустой список, если clear сам по себе подразумевает полную очистку хранилища?

**Comment by coursar** [comment]
`localStorage.setItem("items", JSON.stringify([]));`
