### ISSUE TITLE
Зачем нужен этот файл?

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-ShoppingCalculator#18]
https://github.com/alinagaripova/homework-ShoppingCalculator/blob/907fbf0bcdc6a159b7e7620071ae7c4702ddee92/src/js/lib.js#L1-L29

**Comment by alinagaripova** [comment]
Это я пыталась воспроизвести то, что вы делали в tasktraker в 10 лекции(я пропустила этот день), у вас там также два файла: lib.js и storage.js, но не разобралась и пока закомментировала.

**Comment by coursar** [comment]
удалять надо, а не комментировать ))
