### ISSUE TITLE
Где объект корзины с логикой и классы для покупок?

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-ShoppingCalculator#3]
https://github.com/alinagaripova/homework-ShoppingCalculator/blob/e29db5de905f0e184a1cfad24d32213e4248f942/src/js/app.js#L3-L30

**Comment by alinagaripova** [comment]
Д/З выполнено. Проверьте, пожалуйста.

**Comment by coursar** [comment]
ok
