### ISSUE TITLE
Не работают тесты

### ISSUE THREAD

**Issue by alinagaripova** [alinagaripova/homework-ShoppingCalculator#5]
Добрый вечер! у меня не работают тесты, проверьте, пожалуйста, в чем ошибка.

https://github.com/alinagaripova/homework-ShoppingCalculator/blob/1f89bfb040850e86c2aa7f452f757491c77f6c71/test/app.test.js#L3-L9

**Comment by coursar** [comment]
Что именно не работает?

**Comment by alinagaripova** [comment]
Ожидаю 600, а он считает, что должно быть 0.
Expected: 600
Received: 0
Expected :600
Actual  : 0

**Comment by coursar** [comment]
Потому что вы неправильно используете свои же объекты:
```javascript
import { amount, Product } from "../src/js/lib";

test ('should calculate sum', () => {
    amount.items = [new Product('', 100), new Product('', 200), new Product('', 300)];
    const result = amount.sum();

    expect(result).toBe(600);

});
```
