### ISSUE TITLE
Оформление кода: WebStorm - Ctrl + Alt + L

### ISSUE THREAD

**Issue by coursar** [alinagaripova/homework-ShoppingCalculator#7]
https://github.com/alinagaripova/homework-ShoppingCalculator/blob/36d6443a434127159d56aad247731a042640090d/src/js/app.js#L1-L24

**Comment by alinagaripova** [comment]
Выполнено.

https://github.com/alinagaripova/homework-ShoppingCalculator/blob/fa3298614a18b8e937feb75bd6f0f23843ce6adb/src/js/app.js#L1-L22

**Comment by coursar** [comment]
issue нужно закрывать сообщениями коммитов, а не комментариями в issue
